app:
    resource: '@AppBundle/Controller/'
    type:     'annotation'
    prefix: 'api/'

api:
    resource: '.'
    type:     'api_platform'
    prefix: 'api/'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: 'api/'

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

