app:
    resource: '@AppBundle/Controller/'
    type:     'annotation'

api:
    resource: '.'
    type:     'api_platform'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

